config/routes.rb
Rails.application.routes.draw do
  root "posts#index" 
  resources :sessions, onlu:[:new,:create,:destroy]
  resources :users, only:[:new,:create,:show,:edit,:update]
  resources :favorites, only:[:index,:create,:destroy]
  resources :posts do
    collection do
      post 'confirm'
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true,length: { maximum: 140 }
  validates :image, presence: true
  #mageカラムに、ImageUploaderを紐付けます。
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence:true, length: { maximum: 255 },
            uniqueness: true,
            # このヘルパーは、withオプションで与えられた正規表現と属性の値がマッチするかどうかをテストすることによってバリデーションを行います。
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  # emailを小文字にする処理をコールバックとして検証前に実装
  before_validation { email.downcase! }
  has_secure_password
  validates :password_digest, presence: true, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # セッション用のヘルパーモジュールをincludeして全コントローラで使用できるようにする
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.where(user_id: current_user.id)
  end

  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post_info, only:[:show,:edit,:update,:destroy]

  def index
    @post = Post.all
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def confirm
    @post = current_user.posts.new(post_params)
    render :new if @post.invalid?
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      PostedConfirmationMailer.posted_confirmation(@post).deliver
      redirect_to posts_path, notice:"投稿に成功しました"
    else
      render :new
    end
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  def edit
    if @post.user_id != current_user.id
      redirect_to user_path(current_user.id),
      notice: "アクセス権限がありません"
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice:"編集に成功しました"
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy
    redirect_to user_path, notice:"削除に成功しました"
  end

  private

  def set_post_info
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text,:image,:image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # セッションメソッドを使ってログイン
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show,:edit,:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "登録に成功しました"
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # appcontrollerでincludeされているため全てのコントローラで使用可能
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<% @favorites.each do |fav| %>
  <% if fav.post%>
    <p><%= fav.post.user.name  %></p>
    <p><%= fav.post.text  %></p>
    <P><%= image_tag fav.post.image.url %></p>
    <%= link_to "詳細", post_path(fav.post.id) %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <a href="/posts" class="header_logo">インスタClone</a>
  <nav>
    <ul class="top_menu clearfix">
      <li><%= link_to "投稿一覧", posts_path %></li>
      <li><%= link_to "新規投稿", new_post_path %></li>
      <li><%= link_to "マイページ", user_path(current_user.id) %></li>
      <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
    </ul>
  </nav>
<% else %>
  <a href="/sessions/new" class="header_logo">インスタClone</a>
  <nav>
    <ul class="top_menu">
      <li><%= link_to "ログイン", new_session_path %></li>
      <li><%= link_to "新規登録", new_user_path %></li>
    </ul>
  </nav>
<% end %>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header class="header clearfix">
        <%= render 'layouts/header' %>
    </header>

    <div class="container">

      <%# flashメッセージの表示%>
      <% flash.each do |key, value| %>
        <%# content_tagはタグを動的に生成 %>
        <%# divタグで囲み、受け取ったvalueを表示。classは:dangerや:alertが入る%>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      
      <%= yield %>

    </div>
    
    <footer class="footer">
        <p>Copyright © 2018 All RIGHTS RESERVED.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: choose_new_or_edit, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="post_title">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@post.image.url) if @post.image.url %>
    <%= form.file_field :image%>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<h3>投稿確認</h3>

<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <%= form.hidden_field :text %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>

  <p><%= image_tag @post.image.url if @post.image.url %></p>
  <p><%= @post.text %></p>
  <%= form.submit "登録する" %>
<% end %>

<%= form_with(model: @post, url:new_post_path, local: true, method: :get) do |form| %>
  <%= form.hidden_field :text %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: :back %>
<% end %>

app/views/posts/edit.html.erb
<h1>編集</h1>

<%= render"form" %>

app/views/posts/index.html.erb
<h1>一覧</h1>
<% @post.each do |post| %>
  <div class="card">
    <div class="card-body">
      <p class="card-user"><%= post.user.name %></p>
      <span ><%= image_tag post.user.image, class:"profile_img" %></span>
      <span><%= post.created_at.strftime("%m月%d日%H:%M") %></span>
      <p class="card-text"><%= post.text %></p>         
    </div>
    <%= image_tag post.image.url, class: "card-img-bottom" %>
    <%= link_to '詳細', post_path(post.id) %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1>詳細画面</h1>
<p><%= @post.user.name %>
<p><%= @post.text %></p>
<p><%= image_tag @post.image.url %></p>

<%# お気に入りボタンの表示 %>
<%# 自分の投稿には表示されない %>
<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to '戻る', :back %>

app/views/users/edit.html.erb
<%= form_with(model: @user, url: user_path(params[:id]), local: true) do |f| %>
  <%= image_tag @user.image.url %>
  <p class="chose_image">
  <%= f.file_field :image %>
  </p>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.submit "編集する" %>
<% end %>

app/views/users/new.html.erb
<h1>新規アカウント</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <%# エラーメッセージの表示%>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="chose_image">
    <%= f.label :プロフィール画像 %>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
    <%= f.submit "アカウントを作成" %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<%= form_with(model: @user, local: true, class:"profile") do |form| %>
  <p>ユーザー名:<%= @user.name %></p>
  <p>プロフィール画像:<%= image_tag @user.image.url %></p>
  <p>メールアドレス: <%= @user.email %></p>
  <%= link_to "編集", edit_user_path(@user.id) %>
  <%= link_to "お気に入り一覧", favorites_path %>
<% end %>

<h1>自分の投稿</h1>
<% @user.posts.each do |my_post| %>
  <p><%= my_post.text %></p>
  <p><%= image_tag my_post.image.url %></p>
  <%= link_to "編集", edit_post_path(my_post.id) %>
  <%= link_to "削除", post_path(my_post.id), method: :delete, data: { confirm: "本当に削除しますか？"} %>
<% end %>